# Generated by Django 2.1.2 on 2019-02-05 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alta',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557796)),
        ),
        migrations.AlterField(
            model_name='alta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 569687)),
        ),
        migrations.AlterField(
            model_name='alta',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557851)),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557796)),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557851)),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557796)),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557851)),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557796)),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557851)),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557796)),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557851)),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557796)),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557851)),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557796)),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557851)),
        ),
        migrations.AlterField(
            model_name='ecp',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557796)),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 569010)),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557851)),
        ),
        migrations.AlterField(
            model_name='medicacion_habitual',
            name='descripcion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557796)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557851)),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557796)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 570281)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reinternacion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 570379)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reintervencion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 570476)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557851)),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557796)),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 3, 56, 557851)),
        ),
    ]
