# Generated by Django 2.1.2 on 2019-02-05 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0002_auto_20190205_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397))),
                ('update_date', models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435))),
                ('export_date', models.DateTimeField(blank=True, null=True)),
                ('fecha', models.DateTimeField()),
                ('prioridad', models.CharField(max_length=50)),
                ('incidencia', models.CharField(choices=[('Primer Cirugia', 'Primer Cirugia'), ('Reoperacion', 'Reoperacion'), ('2da Reoperacion', '2da Reoperacion'), ('3ra Reoperacion', '3ra Reoperacion'), ('4ta Reoperacion', '4ta Reoperacion')], default='Primera', max_length=35, verbose_name='Incidencia Cirugia')),
                ('tipo_cirugia', models.CharField(max_length=100)),
                ('peso_cirugia', models.CharField(choices=[('CRM', 'CRM'), ('1_NO_CRM', '1-No CRM'), ('2_CIRUGIA', '2-Cirugias'), ('OTRA MENOR', 'Otra Menor')], default='CRM', max_length=35)),
                ('abordaje', models.CharField(choices=[('Esternotomia mediana', 'Esternotomia mediana'), ('Mini Esternotomia Anterior', 'Mini Esternotomia Anterior'), ('Mini Toracotomia', 'Mini Toracotomia'), ('Subxifoideo', 'Subxifoideo')], max_length=35)),
                ('descripcion', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.AlterModelOptions(
            name='antecedentes',
            options={'verbose_name': 'Antecedentes', 'verbose_name_plural': 'Antecedentes'},
        ),
        migrations.AlterModelOptions(
            name='ayudantes',
            options={'verbose_name': 'Ayudante', 'verbose_name_plural': 'Ayudantes'},
        ),
        migrations.AlterModelOptions(
            name='cirujanos',
            options={'verbose_name': 'Cirujano', 'verbose_name_plural': 'Cirujanos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='abordaje',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='ayudante',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='cirujano',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='incidencia',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='peso_cirugia',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='procedimientos',
        ),
        migrations.RemoveField(
            model_name='cirugia',
            name='tipo_cirugia',
        ),
        migrations.AlterField(
            model_name='alta',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397)),
        ),
        migrations.AlterField(
            model_name='alta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 602126)),
        ),
        migrations.AlterField(
            model_name='alta',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435)),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397)),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435)),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397)),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435)),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397)),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435)),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397)),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435)),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397)),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435)),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397)),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435)),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397)),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 601443)),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397)),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 602631)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reinternacion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 602716)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reintervencion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 602777)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435)),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591397)),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 13, 53, 1, 591435)),
        ),
        migrations.AddField(
            model_name='evento',
            name='alta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Alta'),
        ),
        migrations.AddField(
            model_name='evento',
            name='antecedentes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Antecedentes'),
        ),
        migrations.AddField(
            model_name='evento',
            name='ayudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Ayudantes'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cirugia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Cirugia'),
        ),
        migrations.AddField(
            model_name='evento',
            name='cirujano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Cirujanos'),
        ),
        migrations.AddField(
            model_name='evento',
            name='complicaciones',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Complicaciones'),
        ),
        migrations.AddField(
            model_name='evento',
            name='ecodoppler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Ecodoppler'),
        ),
        migrations.AddField(
            model_name='evento',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Laboratorio'),
        ),
        migrations.AddField(
            model_name='evento',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Clinica'),
        ),
        migrations.AddField(
            model_name='evento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Paciente'),
        ),
        migrations.AddField(
            model_name='evento',
            name='procedimientos',
            field=models.ManyToManyField(to='estadisticas.Procedimiento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='seguimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Seguimiento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='viablilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Viablilidad'),
        ),
    ]
