# Generated by Django 2.1.2 on 2019-02-05 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0003_auto_20190205_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.RemoveField(
            model_name='ayudantes',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='ayudantes',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='ayudantes',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='cirujanos',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='cirujanos',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='cirujanos',
            name='sexo',
        ),
        migrations.AlterField(
            model_name='alta',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='alta',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='alta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 353521)),
        ),
        migrations.AlterField(
            model_name='alta',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alta',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='alta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Alta'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='antecedentes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Antecedentes'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ayudante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Ayudantes'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cirugia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Cirugia'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cirujano',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Cirujanos'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='complicaciones',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Complicaciones'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ecodoppler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Ecodoppler'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='laboratorio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Laboratorio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='seguimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Seguimiento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='viablilidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Viablilidad'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 352832)),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 354030)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reinternacion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 354121)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reintervencion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 354182)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342956), editable=False),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='export_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 15, 20, 7, 342996), editable=False),
        ),
    ]
