# Generated by Django 2.1.2 on 2019-02-05 22:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0004_auto_20190205_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alta',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='alta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 246105)),
        ),
        migrations.AlterField(
            model_name='alta',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='antecedentes_cerebro_vascular',
            field=models.CharField(choices=[('NO', 'No'), ('TIA', 'T.I.A.'), ('ACV', 'A.C.V.'), ('CAROTIDA > 50', 'Carotida > 50 %')], default='NO', max_length=25),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='antecedentes_heredo_familiares',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=15),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='cirugia_cardiaca_previa',
            field=models.CharField(choices=[('NO', 'No'), ('CRM', 'Si CRM previo'), ('VALVULAR', 'Si valvular previo'), ('COMBINADO', 'Si combinado previo'), ('OTRA', 'Si Otra')], default='NO', max_length=25),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='diabetes',
            field=models.CharField(choices=[('NO', 'No'), ('SI-DIETA', 'Si con dieta'), ('SI-MEDICACION', 'Si con medicacion'), ('SI-INSULINA', 'Si con insulina')], default='NO', max_length=15),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='dislipemia',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=15),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='epoc',
            field=models.CharField(choices=[('NO', 'No'), ('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('SEVERO', 'Severo'), ('OTRA', 'Otra'), ('DESCONOCIDO', 'Desconocido')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='hemostasia',
            field=models.CharField(choices=[('NO', 'No'), ('Si_Acenoc_Warf', 'Si_Acenoc_Warf'), ('Si_Heparina_Sodica', 'Si_Heparina_Sodica'), ('Si_Heparina_bajo_peso', 'Si_Heparina_bajo_peso'), ('Si_IIB/IIIA_Tirofiban', 'Si_IIB/IIIA_Tirofiban')], default='NO', max_length=25),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='hipertension',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=15),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='iam',
            field=models.CharField(choices=[('NO', 'No'), ('< 0,25', '< 0,25'), ('< 1', '< 1 Dia'), ('1..7 ', 'de 1 a 7 Dias'), ('8..21', 'de 8 a 21 Dias'), ('>22', 'Mas de 22 dias'), ('>90', 'Mas de 90 dias')], default='NO', max_length=25),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='inmunocomprometido',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='movilidad_reducida',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=2),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='patologia_renal_previa',
            field=models.CharField(choices=[('NO', 'No  cc > 85 ml/min'), ('MODERADO', 'Si Moderada cc > 50 < 80 ml/min'), ('SEVERO', 'Si Severo < 50 ml/min'), ('DIALISIS', 'Si dialisis')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='tabaco',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No'), ('EX+1AÑO', 'Ex+1año'), ('EX-1AÑO', 'Ex-1año')], default='NO', max_length=15),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='vasculopatia_preiferica',
            field=models.CharField(choices=[('NO', 'No'), ('Clau. Itte', 'Clau. Itte'), ('Amputacion', 'Amputacion'), ('Bypass/ATP', 'Bypass/ATP'), ('Indice T/B <0.9 o equivalente', 'Indice T/B <0.9 o equivalente')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='aorta_calcificada',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=2),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='conductos',
            field=models.CharField(choices=[('N/A', 'No corresponde'), ('SITA(1mamaria +/- vena)', 'SITA(1mamaria +/- vena)'), ('BITA(2mamarias)', 'BITA(2mamarias)'), ('SVG(todo vena)', 'SVG(todo vena)'), ('BITA+SVG (2mam+vena)', 'BITA+SVG (2mam+vena)'), ('mamaria+radial', 'mamaria+radial'), ('mamaria+radial+vena', 'mamaria+radial+vena'), ('radial', 'radial')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='extubado_enquirofano',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='hemoderivados_intra',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='aco_alta',
            field=models.CharField(choices=[('Domicilio', 'Domicilio'), ('Tercer Nivel', 'Tercer Nivel'), ('Obito', 'Obito')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='arritmia',
            field=models.CharField(choices=[('NO', 'No'), ('FA <48h ', 'FA <48h '), ('FA >48h ', 'FA >48h '), ('TV/FV ', 'TV/FV '), ('BAV <7dias ', 'BAV < 7dias '), ('MCP definitivo ', 'MCP definitivo '), ('Otra (describir)', 'Otra')], default='NO', max_length=25),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='hiperglucemia',
            field=models.CharField(choices=[('NO', 'No'), ('No (BIC)', 'No (BIC)'), ('Si (Correcciones)', 'Si (Correcciones)')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='infectologicas',
            field=models.CharField(choices=[('NO', 'No '), ('Herida superficial ', 'Herida superficial '), ('mediastinitis ', 'mediastinitis '), ('Safenectomia ', 'Safenectomia '), ('Neumonia ', 'Neumonia '), ('Asociada a catéter ', 'Asociada a catéter '), ('ITU ', 'ITU ')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='inotropicos',
            field=models.CharField(choices=[('NO', 'No'), ('Dopamina', 'Dopamina'), ('Noradrenalina', 'Noradrenalina'), ('Fenilefrina', 'Fenilefrina'), ('Vasopresina', 'Vasopresina'), ('Adrenalina', 'Adrenalina'), ('Milrinona', 'Milrinona'), ('Levosimendan', 'Levosimendan'), ('Dobutamina', 'Dobutamina')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='isquemia_iam',
            field=models.CharField(choices=[('NO', 'No'), ('SI', 'Si'), ('Si ATC', 'Si ATC'), ('Si CRM', 'Si CRM')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='neurologicas',
            field=models.CharField(choices=[('NO', 'No'), ('TIA', 'TIA'), ('ACV sin secuela', 'ACV sin secuela '), ('ACV con secuela', 'ACV con secuela '), ('convulsión', 'convulsión '), ('Sme. Confusional', 'Sme. Confusional ')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='obito_internacion',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='otra',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='plaquetopenia',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='renal',
            field=models.CharField(choices=[('NO', 'No'), ('IRA', 'IRA'), ('Dialisis', 'Dialisis')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='reop_internado',
            field=models.CharField(choices=[('NO', 'No'), ('Sangrado/Taponamiento', 'Sangrado/Taponamiento'), ('Isquemia/IAM', 'Isquemia/IAM'), ('Inestabilidad esternal', 'Inestabilidad esternal'), ('Mediastinitis', 'Mediastinitis'), ('Disfuncion protésica/hemolisis', 'Disfuncion protésica/hemolisis')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='respiratorias',
            field=models.CharField(choices=[('NO', 'No'), ('Si-Neumonia', 'Si-Neumonia'), ('Si-traqueostomia', 'Si-traqueostomia'), ('Si-TEP', 'Si-TEP'), ('SI-EPOC relacionadas', 'SI-EPOC relacionadas'), ('Si-ARM>48h', 'Si-ARM>48h')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='sangrado_medico',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='sme_bajo',
            field=models.CharField(choices=[('NO', 'No'), ('Si(inotrópicos) ', 'Si(inotrópicos) '), ('Si (IABP/BCIAO)', 'Si (IABP/BCIAO)'), ('Si(Asist.Ventricular) ', 'Si(Asist.Ventricular)')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='sme_vasoplejico',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], default='NO', max_length=35),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='transfusiones',
            field=models.ForeignKey(default='NO', on_delete=django.db.models.deletion.PROTECT, to='estadisticas.Transfusiones'),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='hipertension',
            field=models.CharField(choices=[('NO', 'No'), ('Si_PAP_31-55_mmHg', 'Si (PAP 31-55 mmHg)'), ('Si_PAP_>_55_mmHg', 'Si (PAP > 55 mmHg)')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='pato_val_aortica',
            field=models.CharField(choices=[('NO', 'No'), ('Estenosis Aortica', 'Si - Estenosis Aortica'), ('Trivial', 'Si - Insuficiencia Trivial'), ('Leve', 'Si - Insuficiencia Leve'), ('Moderada', 'Si - Insuficiencia Moderada'), ('Severa', 'Si - Insuficiencia Severa')], max_length=25),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='pato_val_mitral',
            field=models.CharField(choices=[('NO', 'No'), ('Estenosis Mitral', 'Si - Estenosis mitral'), ('Trivial', 'Si - Insuficiencia Trivial'), ('Leve', 'Si - Insuficiencia Leve'), ('Moderada', 'Si - Insuficiencia Moderada'), ('Severa', 'Si - Insuficiencia Severa')], max_length=25, verbose_name='Patologia Val. Tricuspide'),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='pato_val_tricuspidea',
            field=models.CharField(choices=[('NO', 'No'), ('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Severa', 'Severa')], max_length=25, verbose_name='Patologia Val. Tricuspide'),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 245124)),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='anticoagulado',
            field=models.CharField(choices=[('NO', 'No'), ('Si-Acenocumarol (Sintrom)', 'Si-Acenocumarol (Sintrom)'), ('SI-Warfarina (Coumadin)', 'SI-Warfarina (Coumadin)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 246924)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reinternacion_cardiaca',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reinternacion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 247039)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reintervencion_cardiaca',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reintervencion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 247103)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='vivo',
            field=models.CharField(choices=[('SI', 'Si'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230781), editable=False),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 19, 25, 0, 230838), editable=False),
        ),
    ]
