# Generated by Django 2.1.2 on 2019-02-05 23:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0005_auto_20190205_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='complicaciones',
            name='cirujia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Cirugia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alta',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='alta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 903179)),
        ),
        migrations.AlterField(
            model_name='alta',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 902473)),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 903790)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reinternacion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 903879)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reintervencion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 903940)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892171), editable=False),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 5, 20, 34, 46, 892209), editable=False),
        ),
    ]
