# Generated by Django 2.1.2 on 2019-02-06 15:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estadisticas', '0007_auto_20190205_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alta',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='alta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 888240)),
        ),
        migrations.AlterField(
            model_name='alta',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='antecedentes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='ayudantes',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='cirugia',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='cirujanos',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='transfusiones',
            field=models.ForeignKey(default='NO', on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Transfusiones'),
        ),
        migrations.AlterField(
            model_name='complicaciones',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='ecodoppler',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='alta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Alta'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='antecedentes',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Antecedentes'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ayudante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Ayudantes'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cirugia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Cirugia'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cirujano',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Cirujanos'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='complicaciones',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Complicaciones'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='ecodoppler',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Ecodoppler'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='laboratorio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Laboratorio'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Clinica'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Paciente'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='seguimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Seguimiento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='viablilidad',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estadisticas.Viablilidad'),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 886792)),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 889860)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reinternacion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 890037)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='reintervencion_fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 890160)),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874095), editable=False),
        ),
        migrations.AlterField(
            model_name='viablilidad',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 12, 11, 15, 874132), editable=False),
        ),
    ]
